---
title: "SuperFarmer3000"
author: "Hanna Kranas, Joanna Zbijewska"
date: "21 października 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Zdefiniowanie niezbednych wartosci:
## R,S,P,C,H,L,B, gdzie R - krolik, S - owca, P - swinia, C - krowa, H - kon, L - maly pies, B - duzy pies
stado_glowne <<- c(60,24,20,12,6,4,2)
stado <<- c(0,0,0,0,0,0,0)
kostka_zielona <- c('R','R','R','R','R','R','S','S','S','P','C','W')
kostka_czerwona <- c('R','R','R','R','R','R','S','S','P','P','H','F')
##gdzie: W - wilk, F - lis; reszta jak wyzej

##Wektory wymian o takiej samej strukturze jak stado i stado_glowne
##Mowia o tym, ile innych zwierza trzeba aby wymienic na dane zwierze
kon <- c(72,12,6,2,1,12,2)
krowa <- c(36,6,3,1,0,6,1)
swinia <- c(12,2,1,0,0,2,0)
owca <- c(6,1,0,0,0,1,0)
maly_pies <- c(6,1,0,0,0,1,0)
duzy_pies <- c(36,6,3,1,0,6,1)

```
```{r}
##FUNKCJE POMOCNICZE
licz_ile_otrzyma <- function(sie_nalezy){
  if (all(sie_nalezy <= stado_glowne)){
    return(sie_nalezy)
  } else {
    sie_nalezy <- ifelse(sie_nalezy <= stado_glowne, sie_nalezy, stado_glowne)
    return(sie_nalezy)
  }
  ##sprawdzanie z bankiem; bierzemy max tyle ile jest w banku.
  ##funkcja zwraca wektor, wiec nalezy robic otrzymane <- licz_ile_otrzyma(otrzymane)
}


zdecyduj <- function(){
  ##funkcja decydujaca czy wymienic i rzucic czy tylko rzucic 
}



wykonaj_czynnosc <- function(co, jak='+'){
  if (jak=='+'){
    stado <<- stado + co
    stado_glowne <<- stado_glowne - co
    ## tu by sie przydalo sprawdzic czy sie wszystko zgadza
  } else {
    stado <<- stado - co
    stado_glowne <<- stado_glowne + co
    ## tu by sie przydalo sprawdzic czy sie wszystko zgadza
  }
  if (!all(stado+stado_glowne==c(60,24,20,12,6,4,2))){
    cat('!!!! BLAD - STADA SIE NIE SUMUJA !!!!')
    break
  }
  ##wez z banku/oddaj do banku/wymien; bierze to co w licz_ile_otrzyma zwrocona
  ##symultanicznie robi operacje na banku i naszym stadzie
  ## sprawdza czy bank+stado sie sumuje odpowiednio
}

zakoncz <- function(x=stado){
  ##funkcja konczaca gre, gdy otrzymane beda zadane wartosci stada
  if(all(stado >= c(1,1,1,1,1,0,0))){
    cat("Wygrales! Koniec gry!")
    return(TRUE)
  } else {
    #########
    suma = 0
    ##6+12+36+72+1 = 127 krolikow (owca, swinia, krowa, kon, krolik)
    for (i in 1:7){
      switch(i,
             "1"={suma <- suma + stado[i]},
             "2"={suma <- suma + 6*stado[i]},
             "3"={suma <- suma + 12*stado[i]},
             "4"={suma <- suma + 36*stado[i]},
             "5"={suma <- suma + 72*stado[i]},
             "6"={suma <- suma + 6*stado[i]},
             "7"={suma <- suma + 36*stado[i]})
    }
    if (suma >= 127){
      cat("Wygrales! Koniec gry!")
      stado <<- c(suma-126,1,1,1,1,0,0)
      stado_glowne <<- (c(60,24,20,12,6,4,2) - stado)
      return(TRUE)
    }
    return(FALSE)
  }
}
##warunek zawarty w tej funkcji musi jeszcze zapewne zamykac petle gry z break()
##ale fajnie jak cos sie wyswietli na koniec
```
```{r}
##FUNKCJE WYMIANY
czy_starczy_na_konia <- function(){
  suma = 0
  for (i in 1:7){
      switch(i,
             "1"={suma <- suma + stado[i]},
             "2"={suma <- suma + 6*stado[i]},
             "3"={suma <- suma + 12*stado[i]},
             "4"={suma <- suma + 36*stado[i]},
             "6"={suma <- suma + 6*stado[i]},
             "7"={suma <- suma + 36*stado[i]},
             suma <- suma)
    }
    if (suma >= 73){
      cat("Starczy na konia i krolika! Wymieniasz")
      ##trzeba dodac petle zeby wymieniac az to niemozliwe
      wykonaj_czynnosc(c(stado[1:4],0,stado[6:7]),'-')
      ##usuwam wszystko ze stada, zeby wymienic na konia i krolika/i
      if ((suma-72)<=60){
        wykonaj_czynnosc(c((suma-72),0,0,0,1,0,0))
        #bierzemy konia, a reszte w krolikach
      } else {
        while((suma-72)>60){
          wykonaj_czynnosc(c(0,1,0,0,0,0,0))
          suma <- suma - 6
          ##to i tak nie powinno sie zdarzyc bo 60+72 to juz wygrana
        }
      }
    } 
  ## jesli nie starczy to nie robimy nic
  }


owce_na_kroliki <- function(z_owiec=FALSE){
  if(z_owiec==TRUE){if(stado[2]>=1 & stado_glowne[1]>=6){
    wymiana <<- c('R')
    za_wymiane <<- c(0,1,0,0,0,0,0)
    return(wymiana)
  }else {
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat('Nie mozna wymienic')
  }}
}

swinie_na_owce <- function(ze_swin=FALSE){
  if(ze_swin==TRUE){if(stado[3]>=1 & stado_glowne[2]>=2){
    wymiana <<- c('SS')
    za_wymiane <<- c(0,0,1,0,0,0,0)
    return(wymiana)
  }else{
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat('Nie mozna wymienic')
  }}
}

##Funkcje "wymiana_cos" maja na celu sprawdzic mozliwosc wymiany
##i zwrocic wartosc mozliwa do wykorzystania dalej
##wyluczaja tez wektory, ktore mozna latwo odjac od stada i dodac do stada glownego
wymiana_owca <- function(b){
  ##funkcja sprawdza, czy podane zwierze mozna wymienic na owce
  ##i czy zwierzat w stadzie tego typu jest wystarczajaco duzo
  ##jesli tak, to podaje jednoelemenowy wektor odpowiadajacy owcy
  if (stado_glowne[2]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  } else {
  switch(b,
         krolik={if(stado[1]>=owca[1]){
           wymiana <<- c('S')
           za_wymiane <<- c(6,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=owca[6]){
           wymiana <<- c('S')
           za_wymiane <<- c(0,0,0,0,0,1,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=owca[2]){
           wymiana <<- c('S')
           za_wymiane <<- c(0,1,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         ##jesli nie, to wyrzuca komunikat
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

wymiana_maly_pies <- function(b){
  if (stado_glowne[6]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  }else {
  ##funkcja jest co do zasady taka sama jak dla wymiana_owca
  switch(b,
         krolik={if(stado[1]>=maly_pies[1]){
           wymiana <<- c('L')
           za_wymiane <<- c(6,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=maly_pies[6]){
           wymiana <<- c('L')
           za_wymiane <<- c(0,0,0,0,0,1,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=maly_pies[2]){
           wymiana <<- c('L')
           za_wymiane <<- c(0,1,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

wymiana_swinia <- function(b){
  ##analogiczna do wymiana_owca
  if (stado_glowne[3]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  }else {
  switch(b,
         krolik={if(stado[1]>=swinia[1]){
           wymiana <<- c('P')
           za_wymiane <<- c(12,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=swinia[6]){
           wymiana <<- c('P')
           za_wymiane <<- c(0,0,0,0,0,2,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=swinia[2]){
           wymiana <<- c('P')
           za_wymiane <<- c(0,2,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         swinia={if(stado[3]>=swinia[3]){
           wymiana <<- c('P')
           za_wymiane <<- c(0,0,1,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

wymiana_krowa <- function(b){
  ##analogiczna do wymiana_owca i wymiana_swinia
  if (stado_glowne[4]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  }else {
  switch(b,
         krolik={if(stado[1]>=krowa[1]){
           wymiana <<- c('C')
           za_wymiane <<- c(36,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=krowa[6]){
           wymiana <<- c('C')
           za_wymiane <<- c(0,0,0,0,0,6,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=krowa[2]){
           wymiana <<- c('C')
           za_wymiane <<- c(0,6,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         swinia={if(stado[3]>=krowa[3]){
           wymiana <<- c('C')
           za_wymiane <<- c(0,0,3,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         krowa={if(stado[4]>=krowa[4]){
           wymiana <<- c('C')
           za_wymiane <<- c(0,0,0,1,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         duzy_pies={if(stado[7]>=krowa[7]){
           wymiana <<- c('C')
           za_wymiane <<- c(0,0,0,0,0,0,1)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

wymiana_duzy_pies <<- function(b){
  if (stado_glowne[7]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  } else {
  ##funkcja co do zasady taka sama jak wymiana_krowa
  switch(b,
         krolik={if(stado[1]>=duzy_pies[1]){
           wymiana <<- c('B')
           za_wymiane <<- c(36,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=duzy_pies[6]){
           wymiana <<- c('B')
           za_wymiane <<- c(0,0,0,0,0,6,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=duzy_pies[2]){
           wymiana <<- c('B')
           za_wymiane <<- c(0,6,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         swinia={if(stado[3]>=duzy_pies[3]){
           wymiana <<- c('B')
           za_wymiane <<- c(0,0,3,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         krowa={if(stado[4]>=duzy_pies[4]){
           wymiana <<- c('B')
           za_wymiane <<- c(0,0,0,1,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         duzy_pies={if(stado[7]>=duzy_pies[7]){
           wymiana <<- c('B')
           za_wymiane <<- c(0,0,0,0,0,0,1)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

wymiana_kon <- function(b){
  ##analogiczna do wymiana_owca, wymiana_swinia i wymiana_krowa
  if (stado_glowne[5]==0){
    wymiana <<- c('pusty')
    za_wymiane <<- c(0,0,0,0,0,0,0)
    cat("Brak w stadzie glownym!")
  }else {
  switch(b,
         krolik={if(stado[1]>=kon[1]){
           wymiana <<- c('H')
           za_wymiane <<- c(72,0,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         maly_pies={if(stado[6]>=kon[6]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,0,0,0,0,12,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         owca={if(stado[2]>=kon[2]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,12,0,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         swinia={if(stado[3]>=kon[3]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,0,6,0,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         krowa={if(stado[4]>=kon[4]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,0,0,2,0,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         kon={if(stado[5]>=kon[5]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,0,0,0,1,0,0)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         duzy_pies={if(stado[7]>=kon[7]){
           wymiana <<- c('H')
           za_wymiane <<- c(0,0,0,0,0,0,2)
           return(wymiana)
         }else{
           wymiana <<- c('pusty')
           za_wymiane <<- c(0,0,0,0,0,0,0)
           cat("Za malo zwierzat na wymiane!")}},
         {wymiana <<- c('pusty')
         za_wymiane <<- c(0,0,0,0,0,0,0)
         cat("Nie istnieje mozliwosc wymiany!")})
  }
}

z_wymiany <- function(zamien = FALSE){
  ##Wylicza wektor zwierzat otrzymanych z wymiany
  W <- c(0,0,0,0,0,0,0)
  if(zamien == TRUE){switch(wymiana,
                            R={W <- c(6,0,0,0,0,0,0)},
                            S={W <- c(0,1,0,0,0,0,0)},
                            SS={W <- c(0,2,0,0,0,0,0)},
                            P={W <- c(0,0,1,0,0,0,0)},
                            C={W <- c(0,0,0,1,0,0,0)},
                            H={W <- c(0,0,0,0,1,0,0)},
                            L={W <- c(0,0,0,0,0,1,0)},
                            B={W <- c(0,0,0,0,0,0,1)},
                            {W <- c(0,0,0,0,0,0,0)})}
  return(W)
}

wymien <- function(z,na){
  ##funkcja dokonujaca wymiany
  ##przyjmowane argumenty sa czytsko symboliczne, a ich wartosc nie ma znaczenia
  ##wlasciwie wymiany dokonuje sie na funkcjach wymien_zwierze('odpowiednie_zwierze')
  wykonaj_czynnosc(z_wymiany(TRUE),'+')
  wykonaj_czynnosc(za_wymiane,'-')
}
```
```{r}
##FUNKCJE RZUCANIA

losuj_rzut_kostek <- function(a=kostka_zielona,b=kostka_czerwona){
  ##funkcja rzucajaca kostkami i tworzaca wynik rzutu (wektor 2 pola)
  wynik <- c(sample(a, 1), sample(b, 1))
  cat(wynik)
  return(wynik)
}

zmiana_na_wektor <- function(wynik){
  ##Funkcja sprawdz wynik rzutu i zamienia go na wektor analogiczny do wektora stada
  ##Najpierw wynik z pierwszej kosci
  switch(wynik[1],
         R={c1 <- c(1,0,0,0,0,0,0)},
         S={c1 <- c(0,1,0,0,0,0,0)},
         P={c1 <- c(0,0,1,0,0,0,0)},
         C={c1 <- c(0,0,0,1,0,0,0)},
         {c1 <- c(0,0,0,0,0,0,0)}
  )
  ##Pozniej wynik z drugiej kosci
  switch(wynik[2],
         R={c2 <- c(1,0,0,0,0,0,0)},
         S={c2 <- c(0,1,0,0,0,0,0)},
         P={c2 <- c(0,0,1,0,0,0,0)},
         H={c2 <- c(0,0,0,0,1,0,0)},
         {c2 <- c(0,0,0,0,0,0,0)}
  )
  ##ten wektor jest abstrakcyjny - jego wartosci ulatwiaja pozniejsze liczenie
  z_rzutu <- (c1+c2)
  return(z_rzutu)
}

rzuc <- function(){
  otrzymane<-c(0,0,0,0,0,0,0)
  kostki<-losuj_rzut_kostek()
  ##co jesli stado puste - wtedy nie trzeba sprawdzac wilkow tylko od razu mozna tu sprawdzac czy kostki sa sobie rowne
  ##
  cat(" , ")
  if (all(stado==0)){
    if (kostki[1]==kostki[2]){
      otrzymane <- licz_ile_otrzyma((zmiana_na_wektor(kostki))/2)
    }
    ## jesli nie sa sobie rowne no to nic nie dostajemy i tak.
  } else {
    if ('W' %in% kostki){
      if ('F' %in% kostki) {
        atak_drapieznika(TRUE,TRUE)
        ## atakuja nas zarowno wilk jak i lis
        ## nie mamy co otrzymac
      } else {
        atak_drapieznika(wilk = TRUE)
        ##atakuje nas tylko wilk
        #######PRZELICZANIE n/2
        wylosowane <- zmiana_na_wektor(kostki)
        otrzymane <- ifelse(wylosowane == 0, 0, trunc((stado+wylosowane)/2))
        otrzymane <- licz_ile_otrzyma(otrzymane)
        ##bo mozemy jeszcze wylosowac cos na drugiej co nam pasuje (np konia)
      }
    } else {
      if ('F' %in% kostki) {
        atak_drapieznika(TRUE)
        ##atakuje nas tylko lis
      }
      ###### PRZELICZANIE n/2
      wylosowane <- zmiana_na_wektor(kostki)
      otrzymane <- ifelse(wylosowane == 0, 0, trunc((stado+wylosowane)/2))
      otrzymane <- licz_ile_otrzyma(otrzymane)
      ##liczy sie zarowno w przypadku lisa jak i kiedy brak drapieznikow
      ##bo mozemy jeszcze wylosowac cos na drugiej co nam pasuje (np owce)
    } 
  }
  if (!all(otrzymane==0)){
    wykonaj_czynnosc(otrzymane)
  } else {
  }
  
  ##funkcja dokonujaca rzutu i reagujaca
}


atak_drapieznika <- function(lis = FALSE, wilk = FALSE){
  if (wilk == TRUE ){
    if (stado[7]>0){
      ##to sie u nas nie zdarza
      wykonaj_czynnosc(c(0,0,0,0,0,0,1),'-')
      ## to oznacza: jeden duzy pies. odejmij od stada (dodaj do glownego)
    } else {
      wykonaj_czynnosc(c(stado[1:4],0,0,0),'-')
      ## to oznacza: wszystkie zwierzeta oprocz konia i psow ktore sa w stadzie. odejmij od stada (dodaj do glownego)
    }
  }
  if (lis == TRUE ){
    if (stado[6]>0){
      wykonaj_czynnosc(c(0,0,0,0,0,1,0),'-')
      ## to oznacza: jeden maly pies. odejmij od stada (dodaj do glownego)
    } else {
      wykonaj_czynnosc(c(stado[1],0,0,0,0,0,0),'-')
      ## to oznacza: wszystkie kroliki ktore sa w stadzie. odejmij od stada (dodaj do glownego)
    }
  }
  ##funkcja przyjmujaca argument lis=True/False i wilk True/False
  ## sprawdza czy mamy psa/psy
  ##odejmuje psa/psy
  ##robi wykonaj_czynnosc i reaguje odpowiednio
}

```

```{r}
## glowna funkcja przeprowadzajaca gre

zagraj <- function(){
  stado_glowne <<- c(60,24,20,12,6,4,2)
  stado <<- c(0,0,0,0,0,0,0)
  repeat{
    ##repeat bo musimy w dwoch miejscach sprawdzac czy nie zebralismy
    if (!all(stado==0)){
      ##jesli stado jest niepuste - bo jak puste to nie ma z czego wymieniac
      ##tutaj wymiany i ich warunki
      ##najpierw sprawdzamy czy starczy na konia i krolika
      czy_starczy_na_konia()
      if (stado[1]>6){
        ##jesli jest wiecej niz 6 krolikow i nie mamy malego psa
        if ((stado[6]==0) & (stado[1]>=9)){
          wymiana_maly_pies('krolik')
          wymien('krolik','maly_pies')
        }
        if (stado[2]>0){
          #jesli juz mamy owce
          wymiana_owca('krolik')
          wymien('krolik','owca')
        }
      } else {
        ##nie mamy krolikow, ale wiecej niz 3 owce i brak malego psa
        if ((stado[1]>3)&(stado[1]==0)&(stado[6]==0)){
          wymiana_maly_pies('owca')
          wymien('owca','maly_pies')
          owce_na_kroliki(TRUE)
          wymien('owca','krolik')
          #wymianakroliki
        }
        if ((stado[3]>0)&(stado[6])){
          #jesli mamy swinie ale nie malego psa
          swinie_na_owce(TRUE)
          wymien('swinia','owca')
          wymiana_maly_pies('owca')
          wymien('owca','maly_pies')
          ##czy tu jeszcze na kroliki? a moze zamienic kolejnoscia warunku sie da
        }
  #trzeba jeszczee dodac warunek ze jak krolikow 60 to wymienic na owce oprocz dziesieciu
      }
    }
    ##eeee tego chyba nie ma co sprawdzac? tylko po rzutach. przy wymianie nie zmienia nam sie ilosc, no chyba ze czegos zabraknie
    if (zakoncz()==TRUE){
      break
    }
    ##rzucamy zawsze, no chyba ze uzbieralismy
    rzuc()
    cat(stado)
    if (zakoncz()==TRUE){
      break
    }
  }
}
```

```{r}
##FUNKCJE STATYSTYK GRY

czas <- data.frame()
mierz_czas <- system.time(zagraj())
##funkcja rbind() powinna dodawać do data frame nowa linijke na końcu
##ale opcji jest duzo, wiec najwyzej sie zamieni, jakby cos nie dzialalo
czas <- replicate(10000,{rbind(czas, mierz_czas)})
  ##funkcja mierzaca czas gry

czas_gry <- czas$user
mediana_i_srednia <- function(x=czas_gry){
  ##funkcja zwracajaca mediane i srednia z wartosci czasow gry
  return(median(czas_gry))
  return(mean(czas_gry))
}

install.packages('ggplot2')
library(ggplot2)
narysuj_wykres <- gplot(x,user,data=czas,color='green',geom='point',ylab="Czas gry",main='Czas trwania gry SuperFarmer')

```
```{r}
##testy
##################
rzuc()
cat(stado)
cat(stado_glowne)
rzuc()
cat(stado)
cat(stado_glowne)
rzuc()
cat(stado)
cat(stado_glowne)
rzuc()
cat(stado)
cat(stado_glowne)
rzuc()
cat(stado)
cat(stado_glowne)
rzuc()
cat(stado)
cat(stado_glowne)
##################
stado <- c(7,2,0,0,0,0,0)
stado_glowne <- c(53,22,20,12,6,4,2)
wymiana_swinia('owca')
wymien('owca','swinia')
cat(stado)
cat(stado_glowne)
wymiana_swinia('owca')
wymien('owca','swinia')
cat(stado)
cat(stado_glowne)
stado <- c(36,0,1,0,0,0,0)
stado_glowne <- c(24,24,19,12,6,4,2)
wymiana_krowa('krolik')
wymien('krolik','krowa')
cat(stado)
cat(stado_glowne)
wymiana_duzy_pies('swinia')
wymien('swinia','duzy_pies')
cat(stado)
cat(stado_glowne)
stado <- c(5,2,3,0,0,0,0)
stado_glowne <- c(55,22,17,12,6,4,2)
owce_na_kroliki(TRUE)
wymien('krolik','owca')
cat(stado)
cat(stado_glowne)
swinie_na_owce(TRUE)
wymien('owca','swinia')
cat(stado)
cat(stado_glowne)
owce_na_kroliki(TRUE)
wymien('krolik','owca')
cat(stado)
cat(stado_glowne)
owce_na_kroliki(TRUE)
wymien('krolik','owca')
cat(stado)
cat(stado_glowne)
stado <- c(57,1,0,0,0,0,0)
stado_glowne <- c(3,23,20,12,6,4,2)
owce_na_kroliki(TRUE)
wymien('krolik','owca')
cat(stado)
cat(stado_glowne)
swinie_na_owce(TRUE)
wymien('owca','swinia')
cat(stado)
cat(stado_glowne)
```
